// Generated by IcedCoffeeScript 108.0.9
(function() {
  'use strict';
  console.log('Installing service worker...');

  self.oninstall = function(e) {
    return console.log('oninstall');
  };

  self.onactivate = function(e) {
    return console.log('onactivate');
  };

  self.onfetch = function(e) {
    var arr;
    arr = e.request.url.split('?soundFallback=');
    if (arr.length === 2) {
      return console.log("sound url: " + arr[0]);
    } else {
      return console.log("url: " + e.request.url);
    }
  };

}).call(this);

//# sourceMappingURL=service-worker.js.map
