// Generated by IcedCoffeeScript 108.0.9
(function() {
  var DEFAULT_THEME;

  DEFAULT_THEME = 'blue-grey';

  angular.module('phoneticsApp', ['ngMaterial', 'angularRipple']).config(function($sceDelegateProvider, $locationProvider, $mdThemingProvider) {
    var t, themes, _i, _len, _results;
    $sceDelegateProvider.resourceUrlWhitelist(['self', 'https://files.parsetfss.com/**']);
    $locationProvider.html5Mode(true);
    $mdThemingProvider.alwaysWatchTheme(true);
    themes = [
      {
        primary: DEFAULT_THEME,
        accent: 'pink'
      }, {
        primary: 'light-green',
        accent: 'pink'
      }, {
        primary: 'light-blue',
        accent: 'orange'
      }, {
        primary: 'amber',
        accent: 'blue'
      }, {
        primary: 'teal',
        accent: 'deep-purple'
      }, {
        primary: 'red',
        accent: 'green'
      }
    ];
    _results = [];
    for (_i = 0, _len = themes.length; _i < _len; _i++) {
      t = themes[_i];
      _results.push($mdThemingProvider.theme(t.primary).primaryPalette(t.primary).accentPalette(t.accent));
    }
    return _results;
  }).factory('ParseServ', function(utils) {
    var Langs, Sounds;
    Parse.initialize('BdvYraypXe3U33UV5mGBRgPmqC2xUyPoP54QgkML', 'kY4MCB6NyGtXjEY6TeAtFWr1zhLv377L3HIiBbas');
    Langs = Parse.Object.extend('Languages');
    Sounds = Parse.Object.extend('Sounds2');
    this.getLangs = function(cb) {
      var query;
      query = new Parse.Query(Langs);
      return query.find({
        success: function(results) {
          return cb(null, results.map(function(r) {
            var palette;
            palette = r.get('palette');
            return {
              id: r.id,
              name: r.get('name'),
              originalName: r.get('originalName'),
              code: r.get('code'),
              toggleLabel: r.get('toggleLabel'),
              palette: palette,
              color: utils.getColor(palette, 'A200')
            };
          }));
        },
        error: function(err) {
          return cb(err, []);
        }
      });
    };
    this.getSounds = function(lang, cb) {
      var query;
      query = new Parse.Query(Sounds);
      query.equalTo('language', lang);
      return query.find({
        success: function(results) {
          return cb(null, results.map(function(r) {
            var name, type, _ref, _ref1;
            name = r.get('name');
            type = r.get('type');
            return {
              name: name,
              type: type,
              altNames: r.get('altNames'),
              parseFile: (_ref = r.get('file')) != null ? (_ref1 = _ref.url()) != null ? _ref1.replace(/^http/, 'https') : void 0 : void 0,
              localFile: "sounds/" + lang.code + "/" + type + "/" + name + ".mp3"
            };
          }));
        },
        error: function(err) {
          return cb(err, []);
        }
      });
    };
    return this;
  }).factory('panels', function() {
    var Panels;
    return new (Panels = (function() {
      var _changeListeners, _defaultHeight;

      _changeListeners = [];

      _defaultHeight = 0;

      Panels.prototype.current = 0;

      Panels.prototype.panels = [];

      function Panels() {}

      Panels.prototype.init = function(panels) {
        this.panels = panels;
        this.panels.unshift({
          name: 'langs',
          toggle: false,
          height: _defaultHeight
        });
        return this.panels.push({
          name: 'about',
          toggle: false,
          height: _defaultHeight
        });
      };

      Panels.prototype.setDefaultHeight = function(defaultHeight) {
        return _defaultHeight = defaultHeight;
      };

      Panels.prototype.setHeight = function(name, height) {
        var s, _i, _len, _ref, _results;
        _ref = this.panels;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (s.name === name) {
            _results.push(s.height = height);
          }
        }
        return _results;
      };

      Panels.prototype.getCurrent = function() {
        return this.current;
      };

      Panels.prototype.setCurrent = function(newCurrent) {
        var cb, _i, _len, _results;
        if (this.panels.length > 0 && newCurrent !== this.current) {
          this.current = newCurrent;
          _results = [];
          for (_i = 0, _len = _changeListeners.length; _i < _len; _i++) {
            cb = _changeListeners[_i];
            _results.push(cb(this.current, this.getInfo(this.current).toggle));
          }
          return _results;
        }
      };

      Panels.prototype.getInfo = function(panelId) {
        return this.panels[panelId];
      };

      Panels.prototype.getBreakPoints = function() {
        return this.panels.reduce((function(p, c, i) {
          p.push(c.height + p[i]);
          return p;
        }), [0]);
      };

      Panels.prototype.getCurrentLang = function() {
        var _ref;
        if ((_ref = this.panels[this.current].name) === 'langs' || _ref === 'about') {
          return null;
        }
        return this.current - 1;
      };

      Panels.prototype.getCurrentLabel = function(state) {
        var tmpLabels, _ref;
        if (this.panels.length === 0) {
          return "loading...";
        }
        tmpLabels = (_ref = this.getInfo(this.current)) != null ? _ref.labels : void 0;
        switch (true) {
          case !tmpLabels:
            return null;
          case tmpLabels.length === 1:
            return tmpLabels[0];
          default:
            return tmpLabels[+state];
        }
      };

      Panels.prototype.cacheToggleStatus = function(state) {
        return this.getInfo(this.current).toggle = state;
      };

      Panels.prototype.getToggleFor = function(idx) {
        return this.getInfo(idx).toggle;
      };

      Panels.prototype.getAll = function() {
        return this.panels;
      };

      Panels.prototype.getLastId = function() {
        var i, v, _i, _len, _ref;
        _ref = this.panels;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          v = _ref[i];
          if (v.name === 'about') {
            return i;
          }
        }
      };

      Panels.prototype.onChange = function(callback) {
        return _changeListeners.push(callback);
      };

      return Panels;

    })());
  }).factory('measurer', function($window, panels) {
    var Measurer;
    return new (Measurer = (function() {
      function Measurer() {
        panels.setDefaultHeight(this.getViewPortHeight());
      }

      Measurer.prototype.getToolbarHeight = function() {
        return 64;
      };

      Measurer.prototype.getWindowHeight = function() {
        return $window.innerHeight;
      };

      Measurer.prototype.getViewPortHeight = function() {
        return this.getWindowHeight() - this.getToolbarHeight();
      };

      Measurer.prototype.getCurrentPanelInfo = function() {
        var b, bottom, breakpoints, i, screenMiddle, scrollToPoint, top, _guessedPanel, _i, _len;
        _guessedPanel = null;
        scrollToPoint = false;
        top = $window.scrollY;
        bottom = top + this.getViewPortHeight();
        breakpoints = panels.getBreakPoints();
        for (i = _i = 0, _len = breakpoints.length; _i < _len; i = ++_i) {
          b = breakpoints[i];
          if (i + 1 < breakpoints.length) {
            if (top >= b && bottom <= breakpoints[i + 1]) {
              _guessedPanel = i;
              break;
            } else if (top < b && bottom > b) {
              screenMiddle = top + this.getViewPortHeight() / 2;
              if (screenMiddle < b) {
                _guessedPanel = i - 1;
                scrollToPoint = breakpoints[_guessedPanel];
                if (panels.getInfo(i - 1).height > this.getViewPortHeight()) {
                  scrollToPoint = breakpoints[i] - this.getViewPortHeight();
                }
              } else if (screenMiddle >= b) {
                _guessedPanel = i;
                scrollToPoint = breakpoints[i];
              }
              break;
            }
          }
        }
        if (_guessedPanel !== null) {
          panels.setCurrent(_guessedPanel);
        }
        return scrollToPoint;
      };

      return Measurer;

    })());
  }).controller('LangCtrl', function($scope, $rootScope, ParseServ, panels, utils) {
    var setStuff;
    $scope.isLastPanel = false;
    $scope.toggleStatus = false;
    $scope.notifyChange = function() {
      return panels.cacheToggleStatus($scope.toggleStatus);
    };
    $scope.getToggleLabel = function() {
      return panels.getCurrentLabel($scope.toggleStatus);
    };
    setStuff = function(theme, title) {
      $scope.title = title;
      $scope.dynamicTheme = theme;
      return $rootScope.currentThemeColor = utils.getColor(theme);
    };
    setStuff(DEFAULT_THEME);
    panels.onChange(function(newGridIdx, toggleStatus) {
      var c;
      $scope.toggleStatus = toggleStatus;
      $scope.isLastPanel = false;
      switch (newGridIdx) {
        case 0:
          setStuff(DEFAULT_THEME);
          break;
        case panels.getLastId():
          setStuff(DEFAULT_THEME, ' ');
          $scope.isLastPanel = true;
          break;
        default:
          c = $scope.langs[newGridIdx - 1];
          setStuff(c.palette, c.name);
      }
      return $scope.$apply();
    });
    return ParseServ.getLangs(function(err, langs) {
      panels.init(langs.map(function(l) {
        return {
          name: l.code,
          toggle: false,
          labels: l.toggleLabel
        };
      }));
      $scope.langs = langs;
      return $scope.$apply();
    });
  }).controller('SoundBoardCtrl', function($scope, ParseServ, utils, panels) {
    var lang;
    $scope.normalizedSoundName = function(sound) {
      return utils.normalize(sound.name);
    };
    $scope.toggleFilter = function(sound) {
      var shouldShow, toggleStatus, _ref, _ref1;
      toggleStatus = panels.getToggleFor($scope.idx + 1);
      if (((_ref = $scope.lang) != null ? _ref.code : void 0) === 'pl') {
        return toggleStatus || sound.name.length === 1;
      }
      if (((_ref1 = $scope.lang) != null ? _ref1.code : void 0) === 'en') {
        shouldShow = sound.type === 'phonetic';
        if (!toggleStatus) {
          shouldShow = !shouldShow;
        }
        return shouldShow;
      }
      return true;
    };
    $scope.getSoundLabel = function(name, altName) {
      var toggleStatus, _ref;
      toggleStatus = panels.getToggleFor($scope.idx + 1);
      if (((_ref = $scope.lang) != null ? _ref.code : void 0) === 'bopo' && toggleStatus) {
        return altName;
      }
      return name;
    };
    lang = new Parse.Object('Languages');
    lang.id = $scope.lang.id;
    lang.code = $scope.lang.code;
    return ParseServ.getSounds(lang, function(err, sounds) {
      $scope.sounds = sounds;
      return $scope.$apply();
    });
  }).directive('aSound', function() {
    return {
      restrict: 'A',
      link: function(scope, element, attr) {
        var player;
        scope.playing = false;
        player = element.find('audio')[0];
        return element.on('click', function() {
          scope.playing = true;
          player.currentTime = 0;
          player.play();
          return player.addEventListener('ended', function() {
            scope.playing = false;
            return scope.$apply();
          });
        });
      }
    };
  }).directive('aPanel', function($window, $timeout, utils, measurer, panels) {
    return {
      restrict: 'A',
      link: function(scope, el, attr) {
        var calculateHeight;
        calculateHeight = function() {
          var clientHeight, idx, loader, minHeight, _ref, _ref1;
          loader = document.getElementById('loader');
          if (loader) {
            setTimeout((function() {
              return loader.remove();
            }), 1200);
          }
          clientHeight = ((_ref = el.find('md-grid-list')[0]) != null ? _ref : el[0]).clientHeight;
          minHeight = Math.max(measurer.getViewPortHeight(), clientHeight);
          if (attr.lastHeight !== minHeight) {
            attr.$set('lastHeight', minHeight);
            idx = (_ref1 = scope.lang) != null ? _ref1.code : void 0;
            if (!idx && scope.langs) {
              idx = 'langs';
            }
            if (idx == null) {
              idx = 'about';
            }
            panels.setHeight(idx, minHeight);
            el.css('min-height', minHeight + 'px');
            $window.scrollBy(0, 1);
          }
        };
        scope.setMinHeight = calculateHeight;
        angular.element($window).bind('resize', utils.debounce(100, calculateHeight));
        return $timeout(calculateHeight);
      }
    };
  }).directive('snap', function($window, utils, measurer) {
    return function(scope, element, attrs) {
      var debouncedScroll;
      debouncedScroll = utils.debounce(100, function() {
        var scrollToPoint;
        scrollToPoint = measurer.getCurrentPanelInfo();
        if (scrollToPoint !== false) {
          return utils.scrollTo(scrollToPoint, 200, utils.easingFunctions.easeInOutQuint);
        }
      });
      return angular.element($window).bind('scroll', function() {
        measurer.getCurrentPanelInfo();
        return debouncedScroll();
      });
    };
  }).directive('preventPopups', function() {
    return function(scope, element, attr) {
      return element.bind('contextmenu', function(e) {
        return scope.$apply(function() {
          return e.preventDefault();
        });
      });
    };
  });

}).call(this);

//# sourceMappingURL=main.js.map
