// Generated by IcedCoffeeScript 108.0.9
(function() {
  'use strict';
  var VERSION, getCacheObject;

  VERSION = 'v1';

  getCacheObject = function(cb) {
    return caches.open("phonetics-" + VERSION).then(cb);
  };

  self.oninstall = function(e) {
    return e.waitUntil(getCacheObject(function(cache) {
      return cache.addAll(['/index.html', '/styles.css', '/js/angular-ripple.js', '/js/main.js', '/js/utils.js']);
    }));
  };

  self.onfetch = function(e) {
    var arr;
    arr = e.request.url.split('?soundFallback=');
    if (arr.length === 2) {
      console.log("sound url: " + arr[0]);
      return e.respondWith(fetch(e.request));
    } else {
      return e.respondWith(caches.match(e.request).then(function(cacheResponse) {
        if (cacheResponse) {
          console.log('cache:', e.request.url);
          return cacheResponse;
        }
        return fetch(e.request).then(function(response) {
          return getCacheObject(function(cache) {
            return cache.put(e.request, response.clone()).then(function() {
              console.log('fresh:', e.request.url);
              return response;
            });
          });
        });
      }));
    }
  };

}).call(this);
